### ISSUE TITLE
[Laravel Elixir] Error: write after end 

### ISSUE THREAD

**Issue by chazmuzz** [skrajewski/laravel-elixir-browserify#10]
I'm getting an error when trying to run a transform.

My gulpfile looks like this:

```javascript
var elixir = require('laravel-elixir'),
    reactify = require('reactify');

require('laravel-elixir-browserify');

elixir(function(mix) {
    mix.browserify("app.js", "public/js", {debug: true, insertGlobals: true, transform: [reactify]});
});
```

And I get this output from gulp:
```bash
[11:53:48] Starting 'default'...
[11:53:48] Starting 'browserify'...
[11:53:48] Finished 'default' after 8.83 ms
[11:53:48] gulp-notify: [Laravel Elixir] Error: write after end
[11:53:48] Finished 'browserify' after 38 ms
```

I get the same error when substituting reactify for debowerify, which it mentioned in the advanced example in the readme.

**Comment by chazmuzz** [comment]
I created an elixir extension that uses vinyl-source-stream rather than vinyl-transform that laravel-elixir-browserify uses.  Reactify transform works doing it this way.  See gist

https://gist.github.com/chazmuzz/7d11a979963745d60894

**Comment by skrajewski** [comment]
Hi @chazmuzz,

thank you for your gist, it was very useful. I replaced vinyl-transform plugin with *vinyl-source-stream* and *vinyl-buffer* and now transform works fine. 

Additionally I provided a small broken change in public API, please see changelog and examples.

Many thanks!

**Comment by chazmuzz** [comment]
Thanks dude. Keep up the good work!
