### ISSUE TITLE
Watching not working with 0.7.0

### ISSUE THREAD

**Issue by waldemarfm** [skrajewski/laravel-elixir-browserify#19]
Watching was working fine with 0.6.0 but I've been waiting for the multiple bundles feature for a while so I updated to 0.7.0.

That feature works fine, but watching no longer works. I followed the docs, added `.watchify()` below my `.browserify()` call, and use `gulp watchify` to trigger watching, but when I save the files with changes nothing happens on terminal. All of the other watchers (sass, etc) trigger as usual though.

**Comment by skrajewski** [comment]
Hi @waldemarfm,

I tested this package with log event from watchify and it worked normally. Could you send me your gulpfile and package.json dependencies with versions?

Thanks!

**Comment by waldemarfm** [comment]
Did more research and it's nothing related to this elixir extension, but the fact I'm using NFS on my virtual machine to mount the project directories. `watchify` currently doesn't detect file changes if it's through a NFS mount, so I'll be watching out for the fix and if necessary I may do a pull request.

[Watchify issue here](https://github.com/substack/watchify/issues/120)

In the interim, is there any way for me to use 0.7.0 but still use the normal elixir watch that does work with NFS?

**Comment by skrajewski** [comment]
Thanks for information, it very useful. I didn't know about this problem before.

Sorry, but you should use version 0.6.0 to rebuild your bundle.

**Comment by Daveawb** [comment]
You can use the normal watch by removing the '.watchify()' call

On Monday, March 16, 2015, Szymon Krajewski <notifications@github.com>
wrote:

> Closed #19
> <https://github.com/skrajewski/laravel-elixir-browserify/issues/19>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skrajewski/laravel-elixir-browserify/issues/19#event-256097285>
> .
>


-- 
Sent from Gmail Mobile
