### ISSUE TITLE
Watchify as a task. Does it really make sense?

### ISSUE THREAD

**Issue by Skyrpex** [skrajewski/laravel-elixir-browserify#21]
Hi!

Executing watchify as a task doesn't make sense to me. I think it should be triggered only when "gulp watch" is called.

Not sure if this can be done with the current elixir API, though...

**Comment by skrajewski** [comment]
Hi @Skyrpex,

I decided to explore latest changes in elixir api. You have right, currently `watchify()` broke standard elixir flow, when you want to run all tasks once. Ideal solution would be run command `gulp watchify` to start watching all changes with watchify wrapper.

Thanks for your your advice :)
