### ISSUE TITLE
Also watch .jsx files

### ISSUE THREAD

**Issue by phaza** [skrajewski/laravel-elixir-browserify#27]
Thank God you've made this.
The default elixir browserify task is so rubbish it's painful.

Anyway, can you add support for watching .jsx files aswell (reactjs files)?

**Comment by skrajewski** [comment]
Hi @phaza,
I think if you add `extensions` option to browserify it will work.

```js
mix.browserify("bootstrap.js", {
        transform: ["babelify"],
        extensions: ["jsx"]
});
```

King regads,
Szymon

**Comment by phaza** [comment]
The problem is that the watcher doesn't trigger when I change .jsx files,
it's only watching .js files.

**Comment by skrajewski** [comment]
I setup test case:

```js
mix.browserify("bootstrap.jsx", {
    extensions: [".jsx"]
});
```

```js
var test = require("./test");
var react = require("./react");

console.log(test);
```

and I run `gulp watchify`. All files have extension __.jsx__. Everything works fine :)

**Comment by phaza** [comment]
Sorry, my mistake. The error wasn't with your plugin at all, but a step that was supposed to happen before it in the pipe. (compile jsx to js)

**Comment by phaza** [comment]
Just wanted to add that your plugin is great. Finally I don't have to struggle with elixir's lack of proper browserify support.
