### ISSUE TITLE
Bundle multiple files

### ISSUE THREAD

**Issue by alvin-nt** [skrajewski/laravel-elixir-browserify#28]
I tried using this with multiple files (with `debowerify`), but it does not work. Any chance of it being supported in the future?

**Comment by skrajewski** [comment]
Hi @alvin-nt,

everything should works. Do you have any errors? Can you show me your *Gulpfile.js*?

**Comment by alvin-nt** [comment]
sorry for the long reply. I think there's a mistake in my side (though I forgot how I fixed it). Now it has been fixed.
