### ISSUE TITLE
Allow different file extensions to be watched

### ISSUE THREAD

**Issue by michaeljcalkins** [skrajewski/laravel-elixir-browserify#30]
I'm using this to run vueify and I'm wondering if you could make an option that would let me define the file extensions I want to watch and if not defined just default to `.js`.

In this case I want to watch for `.vue` files.

https://github.com/skrajewski/laravel-elixir-browserify/blob/master/index.js#L83

`gulpfile.js`

```
var elixir = require('laravel-elixir');
var vueify = require('laravel-elixir-browserify').init("vueify");

elixir(function(mix) {
    mix.sass('app.scss');
    mix.vueify('app.js', {
        insertGlobals: true,
        transform: "vueify",
        output: "public/js"
        extensions: 'js,vue'
    });
});
```

Maybe the extension options equates to something like `**/*.{js,vue}` otherwise defaults to `**/*.{js}`.

**Comment by skrajewski** [comment]
Hm, no problem. This should be in 0.9 release :)

**Comment by michaeljcalkins** [comment]
Woo! You're awesome :)

**Comment by skrajewski** [comment]
I found temporary workaround for this issue - please use `gulp watchify` task instead of `gulp watch`

```js
elixir(function(mix) {
    mix.sass('app.scss');
    mix.vueify('app.js', {
        insertGlobals: true,
        transform: "vueify",
        output: "public/js"
        extensions: ['.js', '.vue']
    });
});
```
